name: Deploy to gitops repo

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Choose deployment type"
        required: true
        type: choice
        options:
          - latest       
          - last_commit   

jobs:

  deploy_latest:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_type == 'latest' }}
    env:
      GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
    steps:
      - name: Clone GitOps repository
        shell: bash

        run: |
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          rm -rf gitops
          git clone https://github.com/mahmoudkhera/grade-api-gitops.git gitops
          cd gitops/helm_chart
          

      - name: update  GitOps repository
        working-directory: gitops/helm_chart
        run: |
          pwd
          export FRONTEND_TAG=latest
          export INVENTORY_TAG=latest
          export NOTIFICATIONS_TAG=latest

          echo " edit SHA: $FRONTEND_TAG"
          sed -i "s|image_tag: .*|image_tag: $FRONTEND_TAG|" values-frontend.yaml
          
          echo " edit SHA: $INVENTORY_TAG"
          sed -i "s|image_tag: .*|image_tag: $INVENTORY_TAG|" values-inventory.yaml
          
          echo " edit SHA: $NOTIFICATIONS_TAG"
          sed -i "s|image_tag: .*|image_tag: $NOTIFICATIONS_TAG|" values-notifactions.yaml

      - name: commit and push to GitOps repository
        working-directory: gitops/helm_chart
        run: |          
          git config --global user.name "mahmoud khera"
          git config --global user.email "mahmoudkhera20@gmail.com"
          git add values-frontend.yaml values-inventory.yaml values-notifactions.yaml

          if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
          fi
          git commit -m "Update image  $(git status |grep -oE "modified|workflows" | tr '\n' ' ')"
          git push -f https://${GIT_TOKEN}@github.com/mahmoudkhera/grade-api-gitops.git main

          echo " Deployed latest tag"


  deploy_last_commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_type == 'last_commit' }}
    env:
      GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
    steps:
      - name: Clone GitOps repository
        shell: bash

        run: |
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          rm -rf gitops
          git clone https://github.com/mahmoudkhera/grade-api-gitops.git gitops
          cd gitops/helm_chart
          
        
      - name: update files to the latest version
        working-directory: gitops/helm_chart
        run : |
          pwd
          # Use current commit SHA as the tag
          export FRONTEND_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mahmoudkhera/devops2-frontend/tags?page_size=1&ordering=last_updated"   | jq  '.results[0].name')
          export INVENTORY_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mahmoudkhera/devops2-inventory/tags?page_size=1&ordering=last_updated"   | jq  '.results[0].name')
          export NOTIFICATIONS_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mahmoudkhera/devops2-notifications/tags?page_size=1&ordering=last_updated"   | jq  '.results[0].name')

          echo " edit SHA: $FRONTEND_TAG"
          sed -i "s|image_tag: .*|image_tag: $FRONTEND_TAG|" values-frontend.yaml
          
          echo " edit SHA: $INVENTORY_TAG"
          sed -i "s|image_tag: .*|image_tag: $INVENTORY_TAG|" values-inventory.yaml
          
          echo " edit SHA: $NOTIFICATIONS_TAG"
          sed -i "s|image_tag: .*|image_tag: $NOTIFICATIONS_TAG|" values-notifactions.yaml

      - name: show images that updated 
        working-directory: gitops/helm_chart
        run:  echo -e "---image updated---\n$(git status | grep -oE "frontend|\inventory\|notifactions")"
    
      - name: commit and pusth to GitOps repository
        working-directory: gitops/helm_chart
        run: | 
          git config --global user.name "mahmoud khera"
          git config --global user.email "mahmoudkhera20@gmail.com"

          git add values-frontend.yaml values-inventory.yaml values-notifactions.yaml

          if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
          fi

          git commit -m "Update image  $(git status |grep -oE "modified|workflows" | tr '\n' ' ')"
          git push -f https://${GIT_TOKEN}@github.com/mahmoudkhera/grade-api-gitops.git main

          echo " Deployed commit SHA: $FRONTEND_TAG"